/**
 * The downloadable CSV template for bulk question import (v2).
 * Client-safe (no server imports) — the wizard turns this into a Blob download.
 *
 * option_e may be left blank for 4-option subjects; correct_answer must point
 * at an option that exists (A–E) and stays blank for extended_response rows.
 * Rows sharing a stimulus_id ref form one stimulus — its title/type/text only
 * need to appear on one row of the group. Asset ref cells accept several refs
 * separated by ";". tags / skill_tags / concept_tags are comma-separated
 * inside one cell. status defaults to draft when blank.
 */
export const CSV_TEMPLATE_FILENAME = 'question-import-template-v2.csv'

export const CSV_TEMPLATE_HEADERS = [
  'external_id',
  'subject',
  'strand',
  'topic',
  'essential_question_type',
  'variant_type',
  'exam_type',
  'year_level',
  'difficulty',
  'marks',
  'time_limit_seconds',
  'answer_format',
  'question_text',
  'option_a',
  'option_b',
  'option_c',
  'option_d',
  'option_e',
  'option_asset_refs_json',
  'option_explanations_json',
  'correct_answer',
  'worked_solution',
  'stimulus_id',
  'stimulus_title',
  'stimulus_type',
  'stimulus_text',
  'stimulus_asset_refs',
  'question_asset_refs',
  'solution_asset_refs',
  'input_method',
  'display_mode',
  'answer_validation_json',
  'rubric_json',
  'skill_tags',
  'concept_tags',
  'tags',
  'source_name',
  'source_paper',
  'source_section',
  'source_question_number',
  'license_notes',
  'asset_generation_prompt',
  'asset_alt_text',
  'asset_spec_json',
  'asset_status',
  'status',
  // Canonical taxonomy v1 (src/lib/taxonomy). All optional; codes not labels.
  'domain_code',
  'subtopic_code',
  'skill_code',
  'pattern_key',
  'question_family',
  'stimulus_format',
  'stimulus_genre',
  'asset_render_method',
  'writing_form',
  'writing_purpose',
  'writing_prompt_stimulus',
  // Asset metadata (optional; append-only). asset_required defaults to true when blank.
  'asset_type',
  'asset_required',
  // Reading question sets (optional; a blank question_set_id keeps the row
  // standalone and behaving exactly as before). Rows sharing a question_set_id
  // form one ordered set; the set title/type/instructions need appear on only
  // one row of the group. option_f / option_g extend answers to A–G.
  'option_f',
  'option_g',
  'question_set_id',
  'question_set_title',
  'question_set_type',
  'question_order_in_set',
  'set_instructions',
  'set_feedback_mode',
  'set_completion_mode',
  'interaction_type',
  'shared_option_pool_id',
  'stimulus_target_label',
  // Passage attribution (distinct from source_name/source_paper, which describe
  // the question's source).
  'stimulus_author',
  'stimulus_source_title',
  'stimulus_source_url',
  'stimulus_attribution_text',
] as const

const EXAMPLE_ROWS: string[][] = [
  [
    'mr-perc-001',
    'Mathematical Reasoning',
    'Number and Algebra',
    'Percentages',
    'Percentage of a quantity',
    '',
    'Selective',
    '6',
    '1',
    '1',
    '60',
    'single_choice',
    'What is 25% of 360?',
    '60',
    '75',
    '90',
    '120',
    '150',
    '',
    '',
    'C',
    '25% is one quarter. One quarter of 360 is 90.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'fractions-of-quantities',
    'percentage-as-fraction',
    'percentages, arithmetic',
    'Practice Paper 3',
    '2024 Sample',
    'Section 1',
    '12',
    '',
    '',
    '',
    '',
    '',
    'draft',
    'number_algebra',
    'percentages',
    '',
    '',
    'standard_multiple_choice',
    'none',
    '',
    'rich_text',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'rd-owl-003',
    'Reading',
    'Literary texts',
    'Poetry',
    'Main idea',
    '',
    'OC',
    '5',
    '2',
    '1',
    '90',
    'single_choice',
    'What is the main feeling the poet expresses about the owl?',
    'Fear of its silent flight.',
    'Admiration for its patience.',
    'Sadness about its loneliness.',
    'Confusion about its habits.',
    '',
    '',
    '',
    'B',
    'The poet repeatedly praises how the owl waits without moving, which shows admiration for its patience.',
    'stim-owl-poem',
    'Night Watcher',
    'poem',
    'The owl sits still as winter stone, / eyes wide against the dark alone...',
    'asset://pending/owl-illustration.png',
    '',
    '',
    '',
    '',
    '',
    '',
    'imagery, main-idea',
    'poetic-voice',
    'poetry, reading',
    'OC Reading Sampler',
    '',
    '',
    '',
    '',
    'A line drawing of an owl perched on a bare branch at night',
    'Owl perched on a branch under a crescent moon',
    '',
    'pending',
    'draft',
    'poetry',
    'poetry_meaning_and_theme',
    '',
    '',
    'standard_multiple_choice',
    'poem',
    'poetry',
    'uploaded_image',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'wr-persuasive-002',
    'Writing',
    'Persuasive writing',
    'Persuasive',
    'Persuasive prompt',
    '',
    'Selective',
    '6',
    '3',
    '20',
    '1800',
    'extended_response',
    'Should school canteens sell only healthy food? Write a persuasive piece arguing your point of view.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'typed_response',
    'full_page',
    '',
    '{"textType":"persuasive","criteria":[{"name":"Ideas and argument","maxMarks":10},{"name":"Structure","maxMarks":5},{"name":"Language and conventions","maxMarks":5}]}',
    'persuasive-devices, paragraphing',
    'audience-awareness',
    'writing, persuasive',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'draft',
    '',
    '',
    '',
    '',
    'extended_writing_task',
    'none',
    '',
    'rich_text',
    'persuasive_response',
    'persuade',
    'scenario',
    '',
    '',
  ],
]

/** Builds a full-width row from a sparse header→value record (blank elsewhere). */
function rowFromRecord(record: Record<string, string>): string[] {
  return CSV_TEMPLATE_HEADERS.map((header) => record[header] ?? '')
}

// Two questions sharing one reading passage set — graded together, feedback
// after the set. Only the first row needs the set/stimulus definition.
const READING_SET_ROWS: string[][] = [
  rowFromRecord({
    external_id: 'rd-set-lighthouse-01',
    subject: 'Reading',
    topic: 'Comprehension',
    essential_question_type: 'Main idea',
    exam_type: 'Selective',
    year_level: '6',
    difficulty: '3',
    answer_format: 'single_choice',
    question_text: 'What is the main reason the keeper stays on the island?',
    option_a: 'He is paid very well.',
    option_b: 'He feels responsible for passing ships.',
    option_c: 'He dislikes the mainland.',
    option_d: 'He is waiting for a letter.',
    correct_answer: 'B',
    worked_solution: 'The passage stresses his duty to ships, not pay or dislike.',
    stimulus_id: 'stim-lighthouse',
    stimulus_title: 'The Lighthouse Keeper',
    stimulus_type: 'passage',
    stimulus_text: 'For thirty years Aldo climbed the spiral stair each dusk...',
    stimulus_author: 'M. Carrow',
    stimulus_source_title: 'Coastal Stories',
    stimulus_source_url: 'https://example.org/coastal-stories',
    stimulus_attribution_text: 'Adapted from Coastal Stories (2019).',
    question_set_id: 'set-lighthouse',
    question_set_title: 'The Lighthouse Keeper',
    question_set_type: 'reading_passage',
    question_order_in_set: '1',
    set_instructions: 'Read the passage, then answer all questions before submitting.',
    set_feedback_mode: 'after_set',
    status: 'draft',
  }),
  rowFromRecord({
    external_id: 'rd-set-lighthouse-02',
    subject: 'Reading',
    topic: 'Comprehension',
    essential_question_type: 'Vocabulary in context',
    exam_type: 'Selective',
    year_level: '6',
    difficulty: '3',
    answer_format: 'single_choice',
    question_text: 'In the passage, "vigil" most nearly means:',
    option_a: 'a long celebration',
    option_b: 'a watchful staying-awake',
    option_c: 'a difficult climb',
    option_d: 'a quiet argument',
    correct_answer: 'B',
    worked_solution: '"Vigil" describes keeping watch through the night.',
    question_set_id: 'set-lighthouse',
    question_order_in_set: '2',
    status: 'draft',
  }),
]

// Sentence insertion: numbered gaps drawing from ONE shared A–G sentence bank.
const SENTENCE_INSERTION_ROWS: string[][] = [
  rowFromRecord({
    external_id: 'rd-insert-23',
    subject: 'Reading',
    topic: 'Cohesion',
    essential_question_type: 'Sentence insertion',
    exam_type: 'Selective',
    year_level: '6',
    difficulty: '4',
    answer_format: 'single_choice',
    question_text: 'Choose the sentence that best fills gap 23.',
    option_a: 'However, the results were inconclusive.',
    option_b: 'This began a decade of careful study.',
    option_c: 'Few noticed at the time.',
    option_d: 'The tide, meanwhile, kept its schedule.',
    option_e: 'Others disagreed entirely.',
    option_f: 'It was, in short, a beginning.',
    option_g: 'No record survives of that winter.',
    correct_answer: 'B',
    worked_solution: 'Gap 23 needs a sentence that opens a period of study.',
    stimulus_id: 'stim-insertion-tides',
    stimulus_title: 'Reading the Tides',
    stimulus_type: 'cloze_passage',
    stimulus_text: 'The observations at gap [23] ... continued until [24] ... and only later [25].',
    question_set_id: 'set-insertion-tides',
    question_set_title: 'Reading the Tides',
    question_set_type: 'sentence_insertion',
    question_order_in_set: '1',
    interaction_type: 'shared_option_single_choice',
    shared_option_pool_id: 'pool-tides',
    stimulus_target_label: '23',
    set_feedback_mode: 'after_set',
    status: 'draft',
  }),
  rowFromRecord({
    external_id: 'rd-insert-24',
    subject: 'Reading',
    topic: 'Cohesion',
    essential_question_type: 'Sentence insertion',
    exam_type: 'Selective',
    year_level: '6',
    difficulty: '4',
    answer_format: 'single_choice',
    question_text: 'Choose the sentence that best fills gap 24.',
    option_a: 'However, the results were inconclusive.',
    option_b: 'This began a decade of careful study.',
    option_c: 'Few noticed at the time.',
    option_d: 'The tide, meanwhile, kept its schedule.',
    option_e: 'Others disagreed entirely.',
    option_f: 'It was, in short, a beginning.',
    option_g: 'No record survives of that winter.',
    correct_answer: 'D',
    worked_solution: 'Gap 24 continues the passage of time.',
    question_set_id: 'set-insertion-tides',
    question_order_in_set: '2',
    interaction_type: 'shared_option_single_choice',
    shared_option_pool_id: 'pool-tides',
    stimulus_target_label: '24',
    status: 'draft',
  }),
]

function escapeCsvCell(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value
}

/** Pads (or trims) a row to the header width so appended columns never misalign. */
function normalizeRow(row: string[]): string[] {
  const cells = [...row]
  while (cells.length < CSV_TEMPLATE_HEADERS.length) {
    cells.push('')
  }
  return cells.slice(0, CSV_TEMPLATE_HEADERS.length)
}

export function buildCsvTemplate(): string {
  const rows = [...EXAMPLE_ROWS, ...READING_SET_ROWS, ...SENTENCE_INSERTION_ROWS]
  const lines = [
    CSV_TEMPLATE_HEADERS.join(','),
    ...rows.map((row) => normalizeRow(row).map(escapeCsvCell).join(',')),
  ]
  return `${lines.join('\n')}\n`
}
