/**
 * The downloadable CSV template for bulk question import (v2).
 * Client-safe (no server imports) — the wizard turns this into a Blob download.
 *
 * option_e may be left blank for 4-option subjects; correct_answer must point
 * at an option that exists (A–E) and stays blank for extended_response rows.
 * Rows sharing a stimulus_id ref form one stimulus — its title/type/text only
 * need to appear on one row of the group. Asset ref cells accept several refs
 * separated by ";". tags / skill_tags / concept_tags are comma-separated
 * inside one cell. status defaults to draft when blank.
 */
export const CSV_TEMPLATE_FILENAME = 'question-import-template-v2.csv'

export const CSV_TEMPLATE_HEADERS = [
  'external_id',
  'subject',
  'strand',
  'topic',
  'essential_question_type',
  'variant_type',
  'exam_type',
  'year_level',
  'difficulty',
  'marks',
  'time_limit_seconds',
  'answer_format',
  'question_text',
  'option_a',
  'option_b',
  'option_c',
  'option_d',
  'option_e',
  'option_asset_refs_json',
  'option_explanations_json',
  'correct_answer',
  'worked_solution',
  'short_explanation',
  'stimulus_id',
  'stimulus_title',
  'stimulus_type',
  'stimulus_text',
  'stimulus_asset_refs',
  'question_asset_refs',
  'solution_asset_refs',
  'input_method',
  'display_mode',
  'answer_validation_json',
  'rubric_json',
  'skill_tags',
  'concept_tags',
  'tags',
  'source_name',
  'source_paper',
  'source_section',
  'source_question_number',
  'license_notes',
  'asset_generation_prompt',
  'asset_alt_text',
  'asset_spec_json',
  'asset_status',
  'status',
  // Canonical taxonomy v1 (src/lib/taxonomy). All optional; codes not labels.
  'domain_code',
  'subtopic_code',
  'skill_code',
  'pattern_key',
  'question_family',
  'stimulus_format',
  'stimulus_genre',
  'asset_render_method',
  'writing_form',
  'writing_purpose',
  'writing_prompt_stimulus',
  // Asset metadata (optional; append-only). asset_required defaults to true when blank.
  'asset_type',
  'asset_required',
] as const

const EXAMPLE_ROWS: string[][] = [
  [
    'mr-perc-001',
    'Mathematical Reasoning',
    'Number and Algebra',
    'Percentages',
    'Percentage of a quantity',
    '',
    'Selective',
    '6',
    '1',
    '1',
    '60',
    'single_choice',
    'What is 25% of 360?',
    '60',
    '75',
    '90',
    '120',
    '150',
    '',
    '',
    'C',
    '25% is one quarter. One quarter of 360 is 90.',
    'A quarter of 360 is 90.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'fractions-of-quantities',
    'percentage-as-fraction',
    'percentages, arithmetic',
    'Practice Paper 3',
    '2024 Sample',
    'Section 1',
    '12',
    '',
    '',
    '',
    '',
    '',
    'draft',
    'number_algebra',
    'percentages',
    '',
    '',
    'standard_multiple_choice',
    'none',
    '',
    'rich_text',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'rd-owl-003',
    'Reading',
    'Literary texts',
    'Poetry',
    'Main idea',
    '',
    'OC',
    '5',
    '2',
    '1',
    '90',
    'single_choice',
    'What is the main feeling the poet expresses about the owl?',
    'Fear of its silent flight.',
    'Admiration for its patience.',
    'Sadness about its loneliness.',
    'Confusion about its habits.',
    '',
    '',
    '',
    'B',
    'The poet repeatedly praises how the owl waits without moving, which shows admiration for its patience.',
    'The poem praises the owl for waiting patiently.',
    'stim-owl-poem',
    'Night Watcher',
    'poem',
    'The owl sits still as winter stone, / eyes wide against the dark alone...',
    'asset://pending/owl-illustration.png',
    '',
    '',
    '',
    '',
    '',
    '',
    'imagery, main-idea',
    'poetic-voice',
    'poetry, reading',
    'OC Reading Sampler',
    '',
    '',
    '',
    '',
    'A line drawing of an owl perched on a bare branch at night',
    'Owl perched on a branch under a crescent moon',
    '',
    'pending',
    'draft',
    'poetry',
    'poetry_meaning_and_theme',
    '',
    '',
    'standard_multiple_choice',
    'poem',
    'poetry',
    'uploaded_image',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'wr-persuasive-002',
    'Writing',
    'Persuasive writing',
    'Persuasive',
    'Persuasive prompt',
    '',
    'Selective',
    '6',
    '3',
    '20',
    '1800',
    'extended_response',
    'Should school canteens sell only healthy food? Write a persuasive piece arguing your point of view.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'typed_response',
    'full_page',
    '',
    '{"textType":"persuasive","criteria":[{"name":"Ideas and argument","maxMarks":10},{"name":"Structure","maxMarks":5},{"name":"Language and conventions","maxMarks":5}]}',
    'persuasive-devices, paragraphing',
    'audience-awareness',
    'writing, persuasive',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'draft',
    '',
    '',
    '',
    '',
    'extended_writing_task',
    'none',
    '',
    'rich_text',
    'persuasive_response',
    'persuade',
    'scenario',
    '',
    '',
  ],
]

function escapeCsvCell(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value
}

export function buildCsvTemplate(): string {
  const lines = [
    CSV_TEMPLATE_HEADERS.join(','),
    ...EXAMPLE_ROWS.map((row) => row.map(escapeCsvCell).join(',')),
  ]
  return `${lines.join('\n')}\n`
}
