-- Seed: expanded question-bank taxonomy v2 (generated from
-- docs/question-taxonomy-v1.csv + docs/essential-question-variants-v1.csv).
-- Idempotent: upserts by slug; never deletes or deactivates existing rows.
--
-- Levels: subjects -> topics (with strand grouping) -> question_types
-- (essential question types, with authoring metadata) -> question_variants.

insert into public.subjects (name, slug, description, sort_order)
values
  ('Reading', 'reading', null, 1),
  ('Mathematical Reasoning', 'mathematical-reasoning', null, 2),
  ('Thinking Skills', 'thinking-skills', null, 3),
  ('Writing', 'writing', null, 4)
on conflict (slug) do update
set name = excluded.name, is_active = true;

with topic_seed(subject_slug, name, slug, strand, sort_order) as (
  values
    ('reading', 'Narrative & Extracts', 'narrative-extracts', 'Prose Comprehension', 1),
    ('reading', 'Poetry', 'poetry', 'Poetry', 2),
    ('reading', 'Paired Extracts', 'paired-extracts', 'Multiple Texts', 3),
    ('reading', 'Information Texts', 'information-texts', 'Factual Texts', 4),
    ('reading', 'Cloze Passage', 'cloze-passage', 'Cloze', 5),
    ('mathematical-reasoning', 'Arithmetic', 'arithmetic', 'Number', 1),
    ('mathematical-reasoning', 'Fractions & Decimals', 'fractions-decimals', 'Number', 2),
    ('mathematical-reasoning', 'Ratio & Rates', 'ratio-rates', 'Number', 3),
    ('mathematical-reasoning', 'Time', 'time', 'Measurement', 4),
    ('mathematical-reasoning', 'Money', 'money', 'Measurement', 5),
    ('mathematical-reasoning', 'Units & Length', 'units-length', 'Measurement', 6),
    ('mathematical-reasoning', 'Area & Perimeter', 'area-perimeter', 'Measurement', 7),
    ('mathematical-reasoning', 'Volume', 'volume', 'Measurement', 8),
    ('mathematical-reasoning', 'Angles', 'angles', 'Geometry', 9),
    ('mathematical-reasoning', 'Symmetry & Transformations', 'symmetry-transformations', 'Geometry', 10),
    ('mathematical-reasoning', 'Coordinates', 'coordinates', 'Geometry', 11),
    ('mathematical-reasoning', 'Patterns', 'patterns', 'Patterns & Algebra', 12),
    ('mathematical-reasoning', 'Algebra', 'algebra', 'Patterns & Algebra', 13),
    ('mathematical-reasoning', 'Tables & Graphs', 'tables-graphs', 'Data', 14),
    ('mathematical-reasoning', 'Statistics', 'statistics', 'Data', 15),
    ('mathematical-reasoning', 'Probability', 'probability', 'Chance', 16),
    ('mathematical-reasoning', 'Problem Solving Strategies', 'problem-solving-strategies', 'Problem Solving', 17),
    ('thinking-skills', 'Argument Analysis', 'argument-analysis', 'Critical Thinking', 1),
    ('thinking-skills', 'Evidence & Reasoning', 'evidence-reasoning', 'Critical Thinking', 2),
    ('thinking-skills', 'Deduction', 'deduction', 'Deductive Logic', 3),
    ('thinking-skills', 'Ordering & Sets', 'ordering-sets', 'Deductive Logic', 4),
    ('thinking-skills', 'Truth Puzzles', 'truth-puzzles', 'Deductive Logic', 5),
    ('thinking-skills', 'Mathematical Analysis', 'mathematical-analysis', 'Numerical Reasoning', 6),
    ('thinking-skills', 'Abstract Reasoning', 'abstract-reasoning', 'Abstract & Spatial', 7),
    ('thinking-skills', 'Spatial Reasoning', 'spatial-reasoning', 'Abstract & Spatial', 8),
    ('writing', 'Imaginative Writing', 'imaginative-writing', 'Written Expression', 1),
    ('writing', 'Persuasive & Discursive Writing', 'persuasive-discursive-writing', 'Written Expression', 2),
    ('writing', 'Informative Writing', 'informative-writing', 'Written Expression', 3),
    ('writing', 'Applied Writing', 'applied-writing', 'Written Expression', 4)
)
insert into public.topics (subject_id, name, slug, strand, sort_order)
select subjects.id, topic_seed.name, topic_seed.slug, topic_seed.strand, topic_seed.sort_order
from topic_seed
join public.subjects on subjects.slug = topic_seed.subject_slug
on conflict (subject_id, slug) do update
set
  name = excluded.name,
  strand = excluded.strand,
  is_active = true;

with type_seed(subject_slug, topic_slug, name, slug, description, common_trap, difficulty_min, difficulty_max, recommended_answer_format, assets_commonly_needed, sort_order) as (
  values
    ('reading', 'narrative-extracts', 'Literal comprehension', 'literal-comprehension', 'Tests retrieval of facts and details stated explicitly in the passage.', 'Students pick an option that sounds plausible instead of checking the exact wording of the text.', 1, 3, 'single_choice', false, 1),
    ('reading', 'narrative-extracts', 'Inference', 'inference', 'Tests drawing a conclusion from clues that are implied but never directly stated.', 'Students choose an answer that is true in general but not actually supported by the passage.', 2, 5, 'single_choice', false, 2),
    ('reading', 'narrative-extracts', 'Main idea', 'main-idea', 'Tests identifying the central point of a passage or paragraph rather than its details.', 'Students select a frequently mentioned detail instead of the idea that covers the whole text.', 2, 4, 'single_choice', false, 3),
    ('reading', 'narrative-extracts', 'Theme', 'theme', 'Tests recognising the underlying message or lesson the writer conveys through the story.', 'Students restate the plot instead of the broader idea the events illustrate.', 3, 5, 'single_choice', false, 4),
    ('reading', 'narrative-extracts', 'Vocabulary in context', 'vocabulary-in-context', 'Tests working out the meaning of a word or phrase as it is used in the passage.', 'Students choose the most common dictionary meaning instead of the meaning that fits the context.', 2, 4, 'single_choice', false, 5),
    ('reading', 'narrative-extracts', 'Tone and attitude', 'tone-and-attitude', 'Tests identifying the narrator''s or writer''s tone and attitude towards the subject.', 'Students confuse a character''s emotion with the tone of the narration itself.', 2, 5, 'single_choice', false, 6),
    ('reading', 'narrative-extracts', 'Language feature effect', 'language-feature-effect', 'Tests explaining why the writer used a technique such as simile or repetition and what effect it creates.', 'Students name the device correctly but choose a vague generic effect that does not fit this passage.', 3, 5, 'single_choice', false, 7),
    ('reading', 'narrative-extracts', 'Text structure', 'text-structure', 'Tests recognising how the passage is organised such as by contrast or by cause and effect.', 'Students describe what the text says rather than how it is arranged.', 2, 4, 'single_choice', false, 8),
    ('reading', 'narrative-extracts', 'Author purpose', 'author-purpose', 'Tests identifying why the author wrote the text such as to persuade or to entertain.', 'Students confuse the topic of the text with the author''s reason for writing it.', 2, 4, 'single_choice', false, 9),
    ('reading', 'narrative-extracts', 'Character motivation', 'character-motivation', 'Tests working out why a character acts or speaks the way they do.', 'Students choose what the character did rather than the reason behind the action.', 2, 4, 'single_choice', false, 10),
    ('reading', 'narrative-extracts', 'Character change', 'character-change', 'Tests tracking how a character''s feelings or views shift across the passage.', 'Students describe only the character''s final state and miss the shift from the beginning.', 2, 5, 'single_choice', false, 11),
    ('reading', 'narrative-extracts', 'Setting and atmosphere', 'setting-and-atmosphere', 'Tests identifying the mood created by the description of a place or time.', 'Students choose a literal detail about the location instead of the feeling it creates.', 2, 4, 'single_choice', false, 12),
    ('reading', 'narrative-extracts', 'Narrative perspective', 'narrative-perspective', 'Tests recognising who is telling the story and how that shapes what the reader knows.', 'Students confuse a first-person narrator with the author of the text.', 2, 4, 'single_choice', false, 13),
    ('reading', 'narrative-extracts', 'Sequencing', 'sequencing', 'Tests placing events from the passage in the order they actually happened.', 'Students use the order events are mentioned even when the text includes a flashback.', 1, 3, 'single_choice', false, 14),
    ('reading', 'narrative-extracts', 'Evidence matching', 'evidence-matching', 'Tests selecting the quotation or line that best supports a given statement.', 'Students pick a quote on the same topic that does not actually prove the statement.', 2, 4, 'single_choice', false, 15),
    ('reading', 'poetry', 'Poetry imagery', 'poetry-imagery', 'Tests interpreting the pictures a poem creates through sensory language.', 'Students read figurative lines literally and choose a surface-level meaning.', 3, 5, 'single_choice', false, 16),
    ('reading', 'poetry', 'Poetry tone', 'poetry-tone', 'Tests identifying the speaker''s mood or attitude across a poem or stanza.', 'Students judge tone from one striking word instead of the poem as a whole.', 3, 5, 'single_choice', false, 17),
    ('reading', 'poetry', 'Symbolism', 'symbolism', 'Tests recognising when an object or image in a poem stands for a bigger idea.', 'Students choose the literal object rather than the idea it represents.', 3, 5, 'single_choice', false, 18),
    ('reading', 'paired-extracts', 'Paired extract comparison', 'paired-extract-comparison', 'Tests comparing ideas or attitudes or techniques across two related extracts.', 'Students answer correctly about one text but ignore what the other text says.', 3, 5, 'single_choice', false, 19),
    ('reading', 'information-texts', 'Information text interpretation', 'information-text-interpretation', 'Tests locating and interpreting information in factual texts such as articles and notices.', 'Students stop at the first matching keyword instead of reading the full condition or exception.', 2, 4, 'single_choice', false, 20),
    ('reading', 'cloze-passage', 'Cloze passage grammar', 'cloze-passage-grammar', 'Tests choosing the word or phrase that fits the grammar of a gap in a passage.', 'Students pick a word that fits the sentence alone but breaks tense or agreement with the surrounding text.', 2, 4, 'single_choice', false, 21),
    ('reading', 'cloze-passage', 'Cloze passage vocabulary', 'cloze-passage-vocabulary', 'Tests choosing the word that best fits the meaning and register of a gap in a passage.', 'Students choose a near-synonym that clashes with the tone or collocations around the gap.', 2, 5, 'single_choice', false, 22),
    ('mathematical-reasoning', 'arithmetic', 'Arithmetic operations', 'arithmetic-operations', 'Tests accurate addition subtraction multiplication and division with whole numbers.', 'Students misapply order of operations or make regrouping errors under time pressure.', 1, 3, 'single_choice', false, 1),
    ('mathematical-reasoning', 'arithmetic', 'Place value', 'place-value', 'Tests understanding the value of digits and comparing or rounding large numbers.', 'Students confuse the digit itself with its value in that position.', 1, 3, 'single_choice', false, 2),
    ('mathematical-reasoning', 'arithmetic', 'Factors and multiples', 'factors-and-multiples', 'Tests finding factors multiples and using highest common factor or lowest common multiple.', 'Students mix up factors with multiples or forget that 1 and the number itself are factors.', 1, 4, 'single_choice', false, 3),
    ('mathematical-reasoning', 'arithmetic', 'Remainders', 'remainders', 'Tests division problems where the remainder carries meaning such as leftover items or cycles.', 'Students round the quotient instead of interpreting what the remainder means in context.', 2, 4, 'single_choice', false, 4),
    ('mathematical-reasoning', 'fractions-decimals', 'Fractions', 'fractions', 'Tests comparing simplifying and operating with fractions of numbers and quantities.', 'Students add numerators and denominators separately instead of finding a common denominator.', 2, 5, 'single_choice', false, 5),
    ('mathematical-reasoning', 'fractions-decimals', 'Decimals', 'decimals', 'Tests ordering rounding and calculating with decimal numbers.', 'Students judge size by the number of digits so they think 0.25 is greater than 0.5.', 2, 4, 'single_choice', false, 6),
    ('mathematical-reasoning', 'fractions-decimals', 'Percentages', 'percentages', 'Tests finding percentages of quantities and converting between fractions decimals and percentages.', 'Students apply the percentage to the wrong base amount especially after an increase or discount.', 2, 5, 'single_choice', false, 7),
    ('mathematical-reasoning', 'ratio-rates', 'Ratio and proportion', 'ratio-and-proportion', 'Tests sharing quantities in a ratio and scaling recipes maps and mixtures.', 'Students divide by the number of ratio parts incorrectly or attach shares to the wrong person.', 2, 5, 'single_choice', false, 8),
    ('mathematical-reasoning', 'ratio-rates', 'Rates', 'rates', 'Tests reasoning with speed price per unit and other quantities compared per one unit.', 'Students divide the two quantities the wrong way round and get the inverted rate.', 3, 5, 'single_choice', false, 9),
    ('mathematical-reasoning', 'time', 'Time', 'time', 'Tests reading clocks and calculating durations and start or finish times.', 'Students subtract times as if there were 100 minutes in an hour.', 1, 4, 'single_choice', false, 10),
    ('mathematical-reasoning', 'time', 'Timetables', 'timetables', 'Tests reading transport or event timetables to find durations connections and best options.', 'Students read the wrong row or column or ignore that a service does not run at the needed time.', 2, 4, 'single_choice', false, 11),
    ('mathematical-reasoning', 'money', 'Money', 'money', 'Tests calculating totals change discounts and best-buy comparisons with money.', 'Students compare prices without converting to the same quantity or unit first.', 1, 4, 'single_choice', false, 12),
    ('mathematical-reasoning', 'units-length', 'Unit conversion', 'unit-conversion', 'Tests converting between metric units of length mass and capacity.', 'Students multiply when they should divide because they forget which unit is larger.', 2, 4, 'single_choice', false, 13),
    ('mathematical-reasoning', 'units-length', 'Length', 'length', 'Tests measuring estimating and calculating with lengths and distances.', 'Students mix units mid-calculation such as adding metres to centimetres directly.', 1, 3, 'single_choice', false, 14),
    ('mathematical-reasoning', 'area-perimeter', 'Area', 'area', 'Tests finding areas of rectangles triangles and composite shapes.', 'Students confuse area with perimeter or forget to split a composite shape before calculating.', 2, 4, 'single_choice', false, 15),
    ('mathematical-reasoning', 'area-perimeter', 'Perimeter', 'perimeter', 'Tests finding the distance around straight-sided shapes including composite ones.', 'Students leave out hidden or unlabelled sides of an L-shaped figure.', 2, 4, 'single_choice', false, 16),
    ('mathematical-reasoning', 'volume', 'Volume', 'volume', 'Tests finding volume and capacity of rectangular prisms and counting unit cubes.', 'Students count only the visible cubes in a diagram and miss the hidden ones.', 2, 4, 'single_choice', false, 17),
    ('mathematical-reasoning', 'angles', 'Angles', 'angles', 'Tests estimating measuring and calculating angles on lines and inside shapes.', 'Students assume a diagram is drawn to scale instead of using angle rules.', 2, 4, 'single_choice', false, 18),
    ('mathematical-reasoning', 'symmetry-transformations', 'Symmetry', 'symmetry', 'Tests identifying lines of symmetry and completing symmetrical figures.', 'Students count rotational matches as extra lines of symmetry.', 1, 3, 'single_choice', false, 19),
    ('mathematical-reasoning', 'symmetry-transformations', 'Transformations', 'transformations', 'Tests recognising and applying translations reflections and rotations of shapes.', 'Students reflect a shape across the wrong axis or confuse a rotation with a reflection.', 2, 4, 'single_choice', false, 20),
    ('mathematical-reasoning', 'coordinates', 'Coordinates', 'coordinates', 'Tests plotting and reading points on a grid and reasoning about positions.', 'Students swap the across and up values and plot the reversed point.', 2, 4, 'single_choice', false, 21),
    ('mathematical-reasoning', 'patterns', 'Patterns and sequences', 'patterns-and-sequences', 'Tests continuing number or shape patterns and finding a rule for later terms.', 'Students find the step between terms but extend by counting one term short.', 2, 5, 'single_choice', false, 22),
    ('mathematical-reasoning', 'algebra', 'Algebraic reasoning', 'algebraic-reasoning', 'Tests reasoning about relationships between unknown quantities described in words or symbols.', 'Students assign a number too early instead of comparing the quantities in general.', 3, 5, 'single_choice', false, 23),
    ('mathematical-reasoning', 'algebra', 'Missing values', 'missing-values', 'Tests finding the unknown number that makes a statement or diagram true.', 'Students apply the operation instead of its inverse when working back to the unknown.', 2, 4, 'single_choice', false, 24),
    ('mathematical-reasoning', 'algebra', 'Equations', 'equations', 'Tests solving simple equations and balancing both sides of a number sentence.', 'Students change one side of the equation without doing the same to the other.', 2, 4, 'single_choice', false, 25),
    ('mathematical-reasoning', 'tables-graphs', 'Data tables', 'data-tables', 'Tests reading comparing and combining values presented in tables.', 'Students read the correct row but the wrong column or ignore the table''s units.', 1, 4, 'single_choice', false, 26),
    ('mathematical-reasoning', 'tables-graphs', 'Column graphs', 'column-graphs', 'Tests reading and comparing values shown in column or bar graphs.', 'Students misread the scale when columns fall between labelled gridlines.', 1, 3, 'single_choice', true, 27),
    ('mathematical-reasoning', 'tables-graphs', 'Line graphs', 'line-graphs', 'Tests interpreting trends and specific values on line graphs over time.', 'Students read the value at the wrong point or confuse the steepness of a line with its height.', 2, 4, 'single_choice', true, 28),
    ('mathematical-reasoning', 'tables-graphs', 'Pie charts', 'pie-charts', 'Tests interpreting proportions and calculating quantities from sector graphs.', 'Students treat a sector''s percentage as the actual quantity without using the total.', 2, 4, 'single_choice', true, 29),
    ('mathematical-reasoning', 'statistics', 'Averages', 'averages', 'Tests calculating and reasoning with the mean of a data set including reverse problems.', 'Students forget that changing one value changes the total and recompute the mean incorrectly.', 2, 5, 'single_choice', false, 30),
    ('mathematical-reasoning', 'probability', 'Probability', 'probability', 'Tests describing and comparing the likelihood of events as fractions or in words.', 'Students count favourable outcomes but forget to count the total number of outcomes.', 2, 4, 'single_choice', false, 31),
    ('mathematical-reasoning', 'problem-solving-strategies', 'Systematic counting', 'systematic-counting', 'Tests counting arrangements combinations or cases in an organised way.', 'Students list cases at random and either miss possibilities or count some twice.', 3, 5, 'single_choice', false, 32),
    ('mathematical-reasoning', 'problem-solving-strategies', 'Working backwards', 'working-backwards', 'Tests undoing a chain of operations from a final result to find the starting value.', 'Students apply the original operations forward instead of inverting them in reverse order.', 3, 5, 'single_choice', false, 33),
    ('mathematical-reasoning', 'problem-solving-strategies', 'Multi-step word problems', 'multi-step-word-problems', 'Tests combining several operations and pieces of information to solve a worded problem.', 'Students stop after an intermediate step and choose that partial answer.', 3, 5, 'single_choice', false, 34),
    ('thinking-skills', 'argument-analysis', 'Identify conclusion', 'identify-conclusion', 'Tests locating the main claim an argument is trying to establish.', 'Students choose a reason or piece of evidence instead of the claim it supports.', 2, 4, 'single_choice', false, 1),
    ('thinking-skills', 'argument-analysis', 'Identify reason', 'identify-reason', 'Tests finding the statement that is offered as support for the conclusion.', 'Students choose background information rather than a statement doing supporting work.', 2, 4, 'single_choice', false, 2),
    ('thinking-skills', 'argument-analysis', 'Strengthen argument', 'strengthen-argument', 'Tests choosing the new statement that most supports the argument''s conclusion.', 'Students choose a statement that merely repeats the conclusion instead of adding support.', 3, 5, 'single_choice', false, 3),
    ('thinking-skills', 'argument-analysis', 'Weaken argument', 'weaken-argument', 'Tests choosing the new statement that most undermines the argument''s conclusion.', 'Students choose a statement that attacks the topic in general rather than the specific reasoning.', 3, 5, 'single_choice', false, 4),
    ('thinking-skills', 'argument-analysis', 'Identify assumption', 'identify-assumption', 'Tests finding the unstated idea the argument needs in order to work.', 'Students choose a stated reason instead of the missing link that is never said.', 3, 5, 'single_choice', false, 5),
    ('thinking-skills', 'argument-analysis', 'Identify flaw', 'identify-flaw', 'Tests spotting the mistake in reasoning that makes an argument unsound.', 'Students say the conclusion is false instead of explaining why the reasoning fails.', 3, 5, 'single_choice', false, 6),
    ('thinking-skills', 'evidence-reasoning', 'Evaluate evidence', 'evaluate-evidence', 'Tests judging whether given evidence actually supports a claim and how strongly.', 'Students accept evidence that is related to the topic but does not bear on the claim.', 3, 5, 'single_choice', false, 7),
    ('thinking-skills', 'evidence-reasoning', 'Cause and effect', 'cause-and-effect', 'Tests distinguishing genuine causes from things that merely happen together.', 'Students assume that because two things occur together one must cause the other.', 3, 5, 'single_choice', false, 8),
    ('thinking-skills', 'evidence-reasoning', 'Drawing conclusions', 'drawing-conclusions', 'Tests selecting the conclusion best supported by a set of given facts.', 'Students choose a conclusion that goes further than the facts allow.', 2, 5, 'single_choice', false, 9),
    ('thinking-skills', 'deduction', 'Must be true', 'must-be-true', 'Tests identifying what necessarily follows from a set of statements.', 'Students choose what is probably true rather than what is guaranteed.', 3, 5, 'single_choice', false, 10),
    ('thinking-skills', 'deduction', 'Cannot be true', 'cannot-be-true', 'Tests identifying which option contradicts the given statements.', 'Students reject an option that is merely unstated rather than actually impossible.', 3, 5, 'single_choice', false, 11),
    ('thinking-skills', 'deduction', 'Conditional logic', 'conditional-logic', 'Tests reasoning correctly with if-then statements and their consequences.', 'Students reverse the conditional and assume the converse must also hold.', 3, 5, 'single_choice', false, 12),
    ('thinking-skills', 'deduction', 'Syllogisms', 'syllogisms', 'Tests combining two or more general statements to reach a valid conclusion.', 'Students let real-world knowledge override what the premises actually allow.', 3, 5, 'single_choice', false, 13),
    ('thinking-skills', 'ordering-sets', 'Ordering', 'ordering', 'Tests placing people or objects in sequence from a set of positional clues.', 'Students fix an order from the first clues and never test it against the later ones.', 2, 5, 'single_choice', false, 14),
    ('thinking-skills', 'ordering-sets', 'Ranking', 'ranking', 'Tests deducing relative rank such as fastest or tallest from comparative clues.', 'Students treat a relative clue as an exact position and over-commit early.', 2, 5, 'single_choice', false, 15),
    ('thinking-skills', 'ordering-sets', 'Set logic', 'set-logic', 'Tests reasoning about membership and overlap between groups described in words.', 'Students assume all members of one group belong to another when only some do.', 3, 5, 'single_choice', false, 16),
    ('thinking-skills', 'ordering-sets', 'Venn reasoning', 'venn-reasoning', 'Tests reasoning about counts and regions where categories overlap.', 'Students double-count items that belong to more than one category.', 3, 5, 'single_choice', false, 17),
    ('thinking-skills', 'truth-puzzles', 'Truth tellers and liars', 'truth-tellers-and-liars', 'Tests deducing who is honest and who is lying from their statements.', 'Students take one speaker''s statement at face value instead of testing each possibility.', 3, 5, 'single_choice', false, 18),
    ('thinking-skills', 'mathematical-analysis', 'Pattern recognition', 'pattern-recognition', 'Tests spotting the numeric rule linking terms in an unfamiliar sequence or array.', 'Students match the first two terms to a rule and never check it on the rest.', 2, 5, 'single_choice', false, 19),
    ('thinking-skills', 'mathematical-analysis', 'Rule deduction', 'rule-deduction', 'Tests working out the hidden operation a machine or code applies to inputs.', 'Students find a rule that fits one example and assume it fits all of them.', 3, 5, 'single_choice', false, 20),
    ('thinking-skills', 'mathematical-analysis', 'Mathematical analysis', 'mathematical-analysis', 'Tests multi-step numeric reasoning where the method must be devised not just applied.', 'Students grab the numbers and apply a familiar operation without modelling the situation.', 3, 5, 'single_choice', false, 21),
    ('thinking-skills', 'mathematical-analysis', 'Table reasoning', 'table-reasoning', 'Tests deducing missing information or conclusions from structured numeric tables.', 'Students answer from a single cell instead of cross-checking rows and totals.', 3, 5, 'single_choice', false, 22),
    ('thinking-skills', 'mathematical-analysis', 'Data sufficiency', 'data-sufficiency', 'Tests judging whether the given information is enough to answer a question.', 'Students solve for one possible answer and assume that means the data is sufficient.', 3, 5, 'single_choice', false, 23),
    ('thinking-skills', 'abstract-reasoning', 'Abstract sequences', 'abstract-sequences', 'Tests finding the rule in a sequence of shapes and choosing what comes next.', 'Students track only one feature such as shape and miss a second changing feature such as shading.', 2, 5, 'single_choice', true, 24),
    ('thinking-skills', 'abstract-reasoning', 'Shape analogies', 'shape-analogies', 'Tests applying the relationship between one pair of figures to a new figure.', 'Students choose a figure that resembles the example rather than one that follows the same rule.', 3, 5, 'single_choice', true, 25),
    ('thinking-skills', 'abstract-reasoning', 'Code and symbol rules', 'code-and-symbol-rules', 'Tests decoding how symbols map to properties of figures and applying the mapping.', 'Students match a symbol to the wrong property because two figures share several features.', 3, 5, 'single_choice', true, 26),
    ('thinking-skills', 'spatial-reasoning', 'Rotation and reflection', 'rotation-and-reflection', 'Tests recognising a figure after it has been turned or mirrored.', 'Students accept a mirror image as a rotation of the original figure.', 2, 5, 'single_choice', true, 27),
    ('thinking-skills', 'spatial-reasoning', 'Paper folding', 'paper-folding', 'Tests predicting hole positions or shapes when folded paper is punched and unfolded.', 'Students unfold only one fold and forget the holes duplicate across every fold line.', 3, 5, 'single_choice', true, 28),
    ('thinking-skills', 'spatial-reasoning', '3D views', '3d-views', 'Tests matching solids to their views from the top front or side and to their nets.', 'Students forget that blocks hidden behind others still appear in a different view.', 3, 5, 'single_choice', true, 29),
    ('thinking-skills', 'spatial-reasoning', 'Spatial reasoning', 'spatial-reasoning', 'Tests general visualisation such as assembling pieces or tracking positions in space.', 'Students rely on gut impression instead of checking each option against the figure.', 2, 5, 'single_choice', true, 30),
    ('writing', 'imaginative-writing', 'Narrative', 'narrative', 'Tests crafting an engaging story with structure character and controlled language.', 'Students retell events without a complication or resolution so the story has no shape.', 2, 5, 'extended_response', false, 1),
    ('writing', 'imaginative-writing', 'Description', 'description', 'Tests building a vivid picture of a person place or moment using precise sensory detail.', 'Students list adjectives instead of selecting a few strong details that create a mood.', 2, 5, 'extended_response', false, 2),
    ('writing', 'imaginative-writing', 'Diary entry', 'diary-entry', 'Tests writing a reflective first-person entry with authentic voice and feeling.', 'Students recount the day''s events without showing the writer''s private thoughts and reactions.', 2, 5, 'extended_response', false, 3),
    ('writing', 'imaginative-writing', 'Recount', 'recount', 'Tests retelling an experience in clear sequence with personal comment and detail.', 'Students chain events with then-and-then linking instead of varying pace and sentence openers.', 2, 5, 'extended_response', false, 4),
    ('writing', 'persuasive-discursive-writing', 'Persuasive', 'persuasive', 'Tests arguing a clear position with organised reasons and persuasive techniques.', 'Students state opinions repeatedly instead of developing each reason with evidence or examples.', 2, 5, 'extended_response', false, 5),
    ('writing', 'persuasive-discursive-writing', 'Discursive', 'discursive', 'Tests exploring more than one side of an issue in a balanced and thoughtful way.', 'Students slip into one-sided persuasion instead of genuinely weighing both perspectives.', 2, 5, 'extended_response', false, 6),
    ('writing', 'persuasive-discursive-writing', 'Speech', 'speech', 'Tests writing a spoken address with audience awareness and rhetorical devices.', 'Students write an essay with no sense of a listening audience or spoken rhythm.', 2, 5, 'extended_response', false, 7),
    ('writing', 'persuasive-discursive-writing', 'Letter', 'letter', 'Tests writing a letter with appropriate form register and purpose for its recipient.', 'Students ignore the recipient and purpose so the tone and content do not fit the task.', 2, 5, 'extended_response', false, 8),
    ('writing', 'informative-writing', 'Informative', 'informative', 'Tests explaining a topic clearly with organised facts and an objective tone.', 'Students drift into personal opinion instead of presenting organised information.', 2, 5, 'extended_response', false, 9),
    ('writing', 'informative-writing', 'Newspaper report', 'newspaper-report', 'Tests reporting an event with headline lead paragraph and factual detail in report style.', 'Students tell the event as a story instead of front-loading who what when and where.', 2, 5, 'extended_response', false, 10),
    ('writing', 'informative-writing', 'Advice sheet', 'advice-sheet', 'Tests giving clear practical guidance organised for a reader who needs help.', 'Students write vague general tips instead of specific actionable steps for the situation.', 2, 5, 'extended_response', false, 11),
    ('writing', 'applied-writing', 'Hybrid stimulus response', 'hybrid-stimulus-response', 'Tests responding to an unusual stimulus by choosing and sustaining a fitting form and voice.', 'Students ignore the stimulus after the first line so the response could fit any prompt.', 2, 5, 'extended_response', true, 12)
)
insert into public.question_types (subject_id, topic_id, name, slug, description, common_trap, difficulty_min, difficulty_max, recommended_answer_format, assets_commonly_needed, sort_order)
select
  subjects.id,
  topics.id,
  type_seed.name,
  type_seed.slug,
  type_seed.description,
  type_seed.common_trap,
  type_seed.difficulty_min,
  type_seed.difficulty_max,
  type_seed.recommended_answer_format,
  type_seed.assets_commonly_needed,
  type_seed.sort_order
from type_seed
join public.subjects on subjects.slug = type_seed.subject_slug
left join public.topics on topics.subject_id = subjects.id and topics.slug = type_seed.topic_slug
on conflict (subject_id, slug) do update
set
  topic_id = excluded.topic_id,
  name = excluded.name,
  description = excluded.description,
  common_trap = excluded.common_trap,
  difficulty_min = excluded.difficulty_min,
  difficulty_max = excluded.difficulty_max,
  recommended_answer_format = excluded.recommended_answer_format,
  assets_commonly_needed = excluded.assets_commonly_needed,
  sort_order = excluded.sort_order,
  is_active = true;

with variant_seed(subject_slug, type_slug, name, slug, description, sort_order) as (
  values
    ('thinking-skills', 'strengthen-argument', 'Add supporting evidence', 'add-supporting-evidence', 'A new fact or finding directly backs up the argument''s main claim.', 1),
    ('thinking-skills', 'strengthen-argument', 'Rule out alternative explanation', 'rule-out-alternative-explanation', 'The option eliminates a rival explanation so the argument''s cause is more likely.', 2),
    ('thinking-skills', 'strengthen-argument', 'Confirm hidden assumption', 'confirm-hidden-assumption', 'The option states that an idea the argument quietly relies on is actually true.', 3),
    ('thinking-skills', 'strengthen-argument', 'Provide representative example', 'provide-representative-example', 'A typical case shows the claim holds beyond the single instance given.', 4),
    ('thinking-skills', 'strengthen-argument', 'Increase reliability of source', 'increase-reliability-of-source', 'The option shows the person or study behind the evidence is trustworthy or expert.', 5),
    ('thinking-skills', 'strengthen-argument', 'Show cause precedes effect', 'show-cause-precedes-effect', 'The option confirms the claimed cause happened before the effect appeared.', 6),
    ('thinking-skills', 'weaken-argument', 'Provide counterexample', 'provide-counterexample', 'A specific case where the claim fails casts doubt on the conclusion.', 1),
    ('thinking-skills', 'weaken-argument', 'Offer alternative explanation', 'offer-alternative-explanation', 'The option gives a different cause that explains the same evidence.', 2),
    ('thinking-skills', 'weaken-argument', 'Undermine hidden assumption', 'undermine-hidden-assumption', 'The option shows an idea the argument depends on is false or doubtful.', 3),
    ('thinking-skills', 'weaken-argument', 'Question sample representativeness', 'question-sample-representativeness', 'The option shows the evidence comes from an unusual or too-small group.', 4),
    ('thinking-skills', 'weaken-argument', 'Discredit source reliability', 'discredit-source-reliability', 'The option shows the evidence comes from a biased or unqualified source.', 5),
    ('thinking-skills', 'weaken-argument', 'Show effect occurs without cause', 'show-effect-occurs-without-cause', 'The option shows the outcome happens even when the claimed cause is absent.', 6),
    ('thinking-skills', 'identify-assumption', 'Missing link assumption', 'missing-link-assumption', 'The unstated idea that connects the given reason to the conclusion.', 1),
    ('thinking-skills', 'identify-assumption', 'No alternative assumption', 'no-alternative-assumption', 'The argument assumes no other cause or option could explain the situation.', 2),
    ('thinking-skills', 'identify-assumption', 'Feasibility assumption', 'feasibility-assumption', 'The argument assumes its proposed plan or action can actually be carried out.', 3),
    ('thinking-skills', 'identify-assumption', 'Representativeness assumption', 'representativeness-assumption', 'The argument assumes the example or sample used is typical of the whole group.', 4),
    ('thinking-skills', 'identify-assumption', 'Continuity assumption', 'continuity-assumption', 'The argument assumes present conditions will stay the same in the future.', 5),
    ('thinking-skills', 'identify-assumption', 'Causal assumption', 'causal-assumption', 'The argument assumes one thing causes another rather than merely accompanying it.', 6),
    ('thinking-skills', 'conditional-logic', 'Apply rule forward', 'apply-rule-forward', 'Given the condition holds the student deduces the stated consequence.', 1),
    ('thinking-skills', 'conditional-logic', 'Contrapositive reasoning', 'contrapositive-reasoning', 'Given the consequence fails the student deduces the condition must fail too.', 2),
    ('thinking-skills', 'conditional-logic', 'Converse trap', 'converse-trap', 'Distractors assume the rule works in reverse when it does not.', 3),
    ('thinking-skills', 'conditional-logic', 'Chain of conditionals', 'chain-of-conditionals', 'Two or more if-then rules must be linked to reach the conclusion.', 4),
    ('thinking-skills', 'conditional-logic', 'Only-if condition', 'only-if-condition', 'The rule states a necessary condition and students must not treat it as sufficient.', 5),
    ('thinking-skills', 'conditional-logic', 'Unless statement', 'unless-statement', 'The rule is phrased with unless and must be translated into if-then form.', 6),
    ('thinking-skills', 'ordering', 'Linear order from clues', 'linear-order-from-clues', 'Positional clues fix a complete left-to-right or first-to-last order.', 1),
    ('thinking-skills', 'ordering', 'Relative position deduction', 'relative-position-deduction', 'Only some relative positions are given and one relationship must be deduced.', 2),
    ('thinking-skills', 'ordering', 'Missing position inference', 'missing-position-inference', 'Students identify which position or person cannot be determined from the clues.', 3),
    ('thinking-skills', 'ordering', 'Contradiction elimination', 'contradiction-elimination', 'Students test each option against the clues and eliminate the impossible orders.', 4),
    ('thinking-skills', 'ordering', 'Circular arrangement', 'circular-arrangement', 'People or objects are seated around a circle so left and right depend on facing.', 5),
    ('thinking-skills', 'ordering', 'Order after a change', 'order-after-a-change', 'An established order is altered by a swap or move and the new order is required.', 6),
    ('thinking-skills', 'abstract-sequences', 'Complete the sequence', 'complete-the-sequence', 'Students choose the figure that continues the pattern in the series.', 1),
    ('thinking-skills', 'abstract-sequences', 'Find the odd one out', 'find-the-odd-one-out', 'Students identify the figure that breaks the rule shared by the others.', 2),
    ('thinking-skills', 'abstract-sequences', 'Matrix pattern', 'matrix-pattern', 'Students find the missing cell in a grid where rules run across rows and columns.', 3),
    ('thinking-skills', 'abstract-sequences', 'Rotation rule', 'rotation-rule', 'Each step turns the figure by a fixed amount and students must predict the next turn.', 4),
    ('thinking-skills', 'abstract-sequences', 'Shading rule', 'shading-rule', 'Fill or shading changes in a repeating cycle across the sequence.', 5),
    ('thinking-skills', 'abstract-sequences', 'Shape count rule', 'shape-count-rule', 'The number of sides dots or elements increases or decreases by a fixed rule.', 6),
    ('thinking-skills', 'abstract-sequences', 'Combined two-feature rule', 'combined-two-feature-rule', 'Two features such as rotation and shading change at once and both must be tracked.', 7),
    ('mathematical-reasoning', 'fractions', 'Compare fractions', 'compare-fractions', 'Students order or compare fractions with different denominators.', 1),
    ('mathematical-reasoning', 'fractions', 'Fraction of a quantity', 'fraction-of-a-quantity', 'Students find a fraction of a number or amount in context.', 2),
    ('mathematical-reasoning', 'fractions', 'Equivalent fractions', 'equivalent-fractions', 'Students recognise or create fractions equal in value to a given fraction.', 3),
    ('mathematical-reasoning', 'fractions', 'Mixed number operations', 'mixed-number-operations', 'Students add or subtract with mixed numbers and improper fractions.', 4),
    ('mathematical-reasoning', 'fractions', 'Fraction word problem', 'fraction-word-problem', 'A story context requires setting up and solving a fraction calculation.', 5),
    ('mathematical-reasoning', 'fractions', 'Fraction on a number line', 'fraction-on-a-number-line', 'Students place or read fractions at positions on a number line.', 6),
    ('mathematical-reasoning', 'fractions', 'Remaining part reasoning', 'remaining-part-reasoning', 'Students work with the fraction left over after parts are used or given away.', 7),
    ('mathematical-reasoning', 'percentages', 'Percentage of a quantity', 'percentage-of-a-quantity', 'Students calculate a given percentage of a number or amount.', 1),
    ('mathematical-reasoning', 'percentages', 'Percentage increase or decrease', 'percentage-increase-or-decrease', 'Students apply a rise or fall by a percentage to find the new amount.', 2),
    ('mathematical-reasoning', 'percentages', 'Discount and sale price', 'discount-and-sale-price', 'Students compute a sale price or saving from a percentage discount.', 3),
    ('mathematical-reasoning', 'percentages', 'Conversion between forms', 'conversion-between-forms', 'Students convert among fractions decimals and percentages.', 4),
    ('mathematical-reasoning', 'percentages', 'Reverse percentage', 'reverse-percentage', 'Students find the original amount given the result after a percentage change.', 5),
    ('mathematical-reasoning', 'percentages', 'Percentage comparison', 'percentage-comparison', 'Students compare two quantities or changes expressed as percentages of different bases.', 6),
    ('mathematical-reasoning', 'time', 'Elapsed time', 'elapsed-time', 'Students find the duration between a start time and an end time.', 1),
    ('mathematical-reasoning', 'time', 'Find start or finish time', 'find-start-or-finish-time', 'Given a duration and one endpoint students find the other endpoint.', 2),
    ('mathematical-reasoning', 'time', '24-hour clock conversion', '24-hour-clock-conversion', 'Students convert between 12-hour and 24-hour time formats.', 3),
    ('mathematical-reasoning', 'time', 'Calendar reasoning', 'calendar-reasoning', 'Students reason with days weeks and dates such as finding the day a date falls on.', 4),
    ('mathematical-reasoning', 'time', 'Time unit conversion', 'time-unit-conversion', 'Students convert between seconds minutes hours and days.', 5),
    ('mathematical-reasoning', 'time', 'Overlapping events', 'overlapping-events', 'Students reason about schedules or events that overlap or repeat in cycles.', 6),
    ('mathematical-reasoning', 'data-tables', 'Read a single value', 'read-a-single-value', 'Students locate one value at the intersection of a row and column.', 1),
    ('mathematical-reasoning', 'data-tables', 'Compare rows or columns', 'compare-rows-or-columns', 'Students compare values across rows or columns to find the largest or smallest.', 2),
    ('mathematical-reasoning', 'data-tables', 'Compute total or difference', 'compute-total-or-difference', 'Students add or subtract values from the table to answer the question.', 3),
    ('mathematical-reasoning', 'data-tables', 'Best option under constraint', 'best-option-under-constraint', 'Students choose the cheapest fastest or best row that satisfies a stated condition.', 4),
    ('mathematical-reasoning', 'data-tables', 'Combine two tables', 'combine-two-tables', 'Information from two related tables must be linked to reach the answer.', 5),
    ('mathematical-reasoning', 'data-tables', 'Missing entry from totals', 'missing-entry-from-totals', 'Students deduce a blank cell using row or column totals.', 6),
    ('mathematical-reasoning', 'multi-step-word-problems', 'Two-operation story', 'two-operation-story', 'The problem requires two different operations applied in the right order.', 1),
    ('mathematical-reasoning', 'multi-step-word-problems', 'Sharing and grouping', 'sharing-and-grouping', 'Quantities are shared split or grouped across people or containers in stages.', 2),
    ('mathematical-reasoning', 'multi-step-word-problems', 'Age relationship problem', 'age-relationship-problem', 'Ages now and in the past or future must be related and solved.', 3),
    ('mathematical-reasoning', 'multi-step-word-problems', 'Before-and-after change', 'before-and-after-change', 'A quantity changes through gains and losses and one state must be recovered.', 4),
    ('mathematical-reasoning', 'multi-step-word-problems', 'Combined work or rates', 'combined-work-or-rates', 'Two people or machines work together and their combined progress must be computed.', 5),
    ('mathematical-reasoning', 'multi-step-word-problems', 'Excess and shortage', 'excess-and-shortage', 'Comparing a surplus in one scenario with a shortfall in another pins down the unknown.', 6),
    ('reading', 'inference', 'Infer character feeling', 'infer-character-feeling', 'Students deduce a character''s emotion from actions dialogue or body language.', 1),
    ('reading', 'inference', 'Infer motive', 'infer-motive', 'Students deduce why a character acted from indirect clues in the passage.', 2),
    ('reading', 'inference', 'Infer relationship', 'infer-relationship', 'Students deduce how two characters are connected or how they feel about each other.', 3),
    ('reading', 'inference', 'Infer unstated cause', 'infer-unstated-cause', 'Students deduce the reason behind an event the text describes but never explains.', 4),
    ('reading', 'inference', 'Infer likely outcome', 'infer-likely-outcome', 'Students predict what will most plausibly happen next based on the passage.', 5),
    ('reading', 'inference', 'Infer setting or time', 'infer-setting-or-time', 'Students deduce where or when the passage takes place from embedded details.', 6),
    ('reading', 'main-idea', 'Whole passage main idea', 'whole-passage-main-idea', 'Students identify the central point the entire passage develops.', 1),
    ('reading', 'main-idea', 'Paragraph main idea', 'paragraph-main-idea', 'Students identify the key point of one specified paragraph.', 2),
    ('reading', 'main-idea', 'Best title', 'best-title', 'Students choose the title that best captures the passage as a whole.', 3),
    ('reading', 'main-idea', 'Best summary', 'best-summary', 'Students choose the one-sentence summary that covers the passage without distortion.', 4),
    ('reading', 'main-idea', 'Main idea versus detail', 'main-idea-versus-detail', 'Students distinguish the overarching idea from supporting details offered as distractors.', 5),
    ('reading', 'main-idea', 'Topic sentence identification', 'topic-sentence-identification', 'Students identify the sentence that states the main point of a paragraph.', 6),
    ('writing', 'narrative', 'Continue the story', 'continue-the-story', 'Students extend a given story opening while keeping its voice and situation.', 1),
    ('writing', 'narrative', 'Story from image prompt', 'story-from-image-prompt', 'Students write a story inspired by a picture stimulus.', 2),
    ('writing', 'narrative', 'Story from title', 'story-from-title', 'Students write a story that genuinely fits a given title.', 3),
    ('writing', 'narrative', 'Story with given opening line', 'story-with-given-opening-line', 'Students begin with a supplied first sentence and build a complete story.', 4),
    ('writing', 'narrative', 'Story with given ending line', 'story-with-given-ending-line', 'Students craft a story that arrives naturally at a supplied final sentence.', 5),
    ('writing', 'narrative', 'Twist ending challenge', 'twist-ending-challenge', 'Students write a story engineered to end with a surprising but fair twist.', 6),
    ('writing', 'narrative', 'Story from object prompt', 'story-from-object-prompt', 'Students build a story around a specified object that must matter to the plot.', 7)
)
insert into public.question_variants (question_type_id, name, slug, description, sort_order)
select question_types.id, variant_seed.name, variant_seed.slug, variant_seed.description, variant_seed.sort_order
from variant_seed
join public.subjects on subjects.slug = variant_seed.subject_slug
join public.question_types
  on question_types.subject_id = subjects.id
  and question_types.slug = variant_seed.type_slug
on conflict (question_type_id, slug) do update
set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true;
